### ISSUE TITLE
Use Name Initials for (future) Avatars

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-volunteer#16]
# Summary

As a volunteer, I would like to the avatar icons to not be broken images and instead default to the student's initials.

## Styles

How dashboard looks now:
<img width="408" alt="Dashboard - Oct 6th, 2021" src="https://user-images.githubusercontent.com/12770108/136299297-321d7f25-311c-41b1-a238-f19a021abcc1.png">

How it will look:

<img width="203" alt="Screen Shot 2021-10-10 at 7 01 37 PM" src="https://user-images.githubusercontent.com/12770108/136715737-85fa5084-6e29-4f77-b090-d73f08204b77.png">

All text is in Nunito font. Light purple color is #D1C4E9.

# Criteria for Completion
 - [ ] Instead of broken images, display the students first and last initial where a future profile pic will go

**Comment by rimenes** [comment]
I'm on it
